# Generated by Django 3.2.25 on 2024-04-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupe',
            name='burth_day',
            field=models.DateField(verbose_name='soli_tavalud'),
        ),
        migrations.AlterField(
            model_name='grupe',
            name='number_phone',
            field=models.IntegerField(verbose_name='Raqami_telefon'),
        ),
    ]
